#! /bin/sh
# PCP QA Test No. 1645
# test hinv.dmi metrics fetch
#
# @author Max Dudek (maxdudek@gmail.com)
#

seq=`basename $0`
echo "QA output created by $seq"

# get standard environment, filters and checks
. ./common.product
. ./common.filter
. ./common.check

[ $PCP_PLATFORM = linux ] || _notrun "Linux sysfs_dmi test, only works with Linux"

status=1	# failure is the default!
$sudo rm -rf $tmp.* $seq.full
trap "cd $here; rm -rf $tmp.*; exit \$status" 0 1 2 3 15

# real QA test starts here
scriptpath="$( cd "$(dirname "$0")" ; pwd -P )"
export DMI_PATH_TEST="$scriptpath/linux"
pmda=$PCP_PMDAS_DIR/linux/pmda_linux.so,linux_init

echo "== Checking dmi info using sample data"
pminfo -fL -K clear -K add,60,$pmda hinv.dmi
echo && echo "== done" && echo

# success, all done
status=0
exit
